[app]
name = "Pocket Dictionary"
authors = ["Jim", "Bob"]
version = "0.1"

[window]
title = "Pocket Dictionary"
full-screen = false
resizable = true

[build]
# The directory which contains the web assets.
directory = "dist"